base_url = "https://flatpak.org"
title = "Flatpak"
description = "The future of application distribution"
compile_sass = false
generate_feeds = true
feed_filenames = ["atom.xml"]
minify_html = false
build_search_index = false

taxonomies = []

[slugify]
paths = "safe"

[markdown]

[extra]
keywords = ["flatpak", "linux", "apps", "sandboxing", "xdg-app"]
